# Generated by Django 4.2.16 on 2024-10-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('meta_description', models.TextField()),
                ('news_type', models.CharField(max_length=20)),
                ('news_subcategory', models.CharField(max_length=20)),
                ('media_type', models.CharField(max_length=255)),
                ('image_urls', models.TextField()),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('source', models.CharField(max_length=255)),
                ('last_scraped', models.DateTimeField()),
                ('international', models.BooleanField()),
                ('old', models.BooleanField(blank=True, null=True)),
                ('sentiment', models.CharField(max_length=15)),
                ('views', models.IntegerField(default=0)),
                ('news_score', models.FloatField(default=0.0)),
                ('rating', models.FloatField(default=0.0)),
                ('engagement', models.IntegerField(default=0)),
                ('author', models.CharField(max_length=255)),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'news',
            },
        ),
    ]
